--
-- PostgreSQL database dump
--

\restrict jkf6zoVnQcuKoCEs7h7tXjajYyG8118KgO8qRQf69o6Kjv9xbZ1GkquKAiq5YAr

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: barber_clientes; Type: TABLE DATA; Schema: public; Owner: barberia
--

INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('5214521206246@s.whatsapp.net', 'Cristia Ñ', '4521206246', '2026-09-25 07:29:52.299828', 5, '2026-09-25 16:29:43.933448', NULL, 0, 0, 'Corte de cabello dama', NULL, NULL, NULL, false, 'frecuente', '2026-09-25 07:29:52.299828');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('5214501111805@s.whatsapp.net', 'Cliente Prueba', '4501111805', '2026-09-25 07:29:52.299828', 5, '2026-09-25 16:29:43.933448', NULL, 0, 0, 'Corte desvanecido o tijera', NULL, NULL, NULL, false, 'frecuente', '2026-09-25 07:29:52.299828');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli00@s.whatsapp.net', 'Luis Ángel Ramírez', '454213952', NULL, 5, NULL, 307.13, 0, 2, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli01@s.whatsapp.net', 'Jorge Antonio Mendoza', '486045419', NULL, 16, NULL, 143.48, 0, 0, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli02@s.whatsapp.net', 'Miguel Ángel Torres', '449608006', NULL, 27, NULL, 242.32, 1, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli03@s.whatsapp.net', 'Francisco Javier Salinas', '471523996', NULL, 19, NULL, 200.58, 0, 0, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli04@s.whatsapp.net', 'Roberto Carlos Núñez', '453528668', NULL, 7, NULL, 135.71, 0, 0, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli05@s.whatsapp.net', 'Alejandro Vidal', '476681670', NULL, 15, NULL, 190.44, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli06@s.whatsapp.net', 'Juan Pablo Escobar', '434908921', NULL, 22, NULL, 112.52, 0, 0, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli07@s.whatsapp.net', 'Diego Armando Reyna', '463778684', NULL, 18, NULL, 207.68, 0, 0, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli08@s.whatsapp.net', 'Ricardo Alberto Peña', '415122724', NULL, 17, NULL, 287.06, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli09@s.whatsapp.net', 'Fernando Iván Castillo', '415456919', NULL, 28, NULL, 131.32, 2, 0, NULL, NULL, NULL, NULL, false, 'consulta', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli10@s.whatsapp.net', 'Óscar Eduardo Zamora', '448665079', NULL, 17, NULL, 306.67, 0, 0, NULL, NULL, NULL, NULL, false, 'consulta', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli11@s.whatsapp.net', 'Héctor Manuel Rivas', '439436275', NULL, 21, NULL, 245.77, 0, 0, NULL, NULL, NULL, NULL, false, 'consulta', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli12@s.whatsapp.net', 'Gerardo Adrián Lozano', '485153225', NULL, 6, NULL, 299.58, 0, 0, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli13@s.whatsapp.net', 'Sergio Andrés Villalobos', '416676930', NULL, 5, NULL, 184.12, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli14@s.whatsapp.net', 'Raúl Alejandro Bustos', '441087999', NULL, 13, NULL, 130.27, 0, 0, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli15@s.whatsapp.net', 'María Fernanda Quintero', '427257198', NULL, 14, NULL, 295.39, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli16@s.whatsapp.net', 'Ana Sofía Delgadillo', '426428502', NULL, 11, NULL, 113.87, 0, 1, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli17@s.whatsapp.net', 'Guadalupe Yolanda Rangel', '426551572', NULL, 21, NULL, 180.07, 1, 0, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli18@s.whatsapp.net', 'Verónica Alejandra Ibarra', '439963908', NULL, 8, NULL, 256.73, 0, 1, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli19@s.whatsapp.net', 'Claudia Beatriz Maldonado', '455094892', NULL, 2, NULL, 166.63, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli20@s.whatsapp.net', 'María de los Ángeles Guzmán Barrera', '429259091', NULL, 15, NULL, 296.07, 0, 0, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli21@s.whatsapp.net', 'Ana Patricia Villaseñor y Robles', '464063478', NULL, 26, NULL, 240.96, 0, 0, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli22@s.whatsapp.net', 'Juan Carlos Domínguez Arellano III', '421990915', NULL, 28, NULL, 143.16, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli23@s.whatsapp.net', 'José María Fernández de Córdova y Alcántara', '431747485', NULL, 1, NULL, 285.10, 0, 0, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli24@s.whatsapp.net', 'Brenda Jazmín Huerta', '461264935', NULL, 23, NULL, 189.66, 0, 0, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli25@s.whatsapp.net', 'Pedro Iván Macías', '482461609', NULL, 7, NULL, 273.07, 0, 0, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli26@s.whatsapp.net', 'Tomás Emilio Barragán', '419481293', NULL, 7, NULL, 196.85, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli27@s.whatsapp.net', 'Emiliano Zapata Ríos', '476654986', NULL, 23, NULL, 245.63, 2, 1, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli28@s.whatsapp.net', 'Nicolás Alejandro Buenrostro', '451946875', NULL, 13, NULL, 150.78, 0, 1, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli29@s.whatsapp.net', 'Adrián Felipe Quiroz', '445498497', NULL, 11, NULL, 156.06, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli30@s.whatsapp.net', 'Cristian Eduardo Nápoles', '430091234', NULL, 16, NULL, 250.69, 0, 0, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli31@s.whatsapp.net', 'Daniel Alberto Sepúlveda', '420039329', NULL, 20, NULL, 226.73, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli32@s.whatsapp.net', 'Iván de Jesús Carrillo', '429933866', NULL, 24, NULL, 224.48, 0, 1, NULL, NULL, NULL, NULL, false, 'consulta', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli33@s.whatsapp.net', 'Marco Tulio Esparza', '424599234', NULL, 27, NULL, 89.30, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli34@s.whatsapp.net', 'Rodrigo Alonso Betancourt', '458701189', NULL, 14, NULL, 90.99, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli35@s.whatsapp.net', 'Israel de la Cruz Márquez', '421645288', NULL, 10, NULL, 103.86, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli36@s.whatsapp.net', 'Enrique Yamil Ponce', '485860279', NULL, 11, NULL, 190.23, 0, 1, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli37@s.whatsapp.net', 'Gustavo Adolfo Lemus', '493501287', NULL, 7, NULL, 296.86, 0, 2, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli38@s.whatsapp.net', 'Octavio Ramiro Fuentes', '475915120', NULL, 26, NULL, 155.08, 0, 0, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli39@s.whatsapp.net', 'Bernardo Javier Delgado', '415894762', NULL, 26, NULL, 277.55, 0, 0, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli40@s.whatsapp.net', 'César Augusto Lomelí', '466420674', NULL, 2, NULL, 123.78, 0, 2, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli41@s.whatsapp.net', 'Ángel Gabriel Paredes', '415821082', NULL, 6, NULL, 185.13, 0, 0, NULL, NULL, NULL, NULL, false, 'problematico', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli42@s.whatsapp.net', 'Salvador Uriel Ocampo', '412502556', NULL, 2, NULL, 89.96, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli43@s.whatsapp.net', 'Ramón Alberto Tiscareño', '496567060', NULL, 18, NULL, 180.88, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli44@s.whatsapp.net', 'Efraín Napoleón Guajardo', '467068345', NULL, 15, NULL, 164.07, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli45@s.whatsapp.net', 'Martín Ricardo Covarrubias', '444515164', NULL, 27, NULL, 241.16, 0, 0, NULL, NULL, NULL, NULL, false, 'consulta', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli46@s.whatsapp.net', 'Israel Alejandro Villanueva', '426232857', NULL, 19, NULL, 292.73, 0, 2, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli47@s.whatsapp.net', 'Uriel Sebastián Anaya', '458857015', NULL, 27, NULL, 254.30, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli48@s.whatsapp.net', 'Brayan Alexis Moreno', '432151774', NULL, 9, NULL, 253.35, 0, 0, NULL, NULL, NULL, NULL, false, 'frecuente', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli49@s.whatsapp.net', 'Kevin Yair Estrada', '446759136', NULL, 19, NULL, 111.23, 0, 1, NULL, NULL, NULL, NULL, false, 'en_riesgo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli50@s.whatsapp.net', 'Jonathan Emmanuel Salcedo', '410246934', NULL, 10, NULL, 156.11, 0, 0, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli51@s.whatsapp.net', 'Julio César Villalobos', '486353485', NULL, 13, NULL, 99.60, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli52@s.whatsapp.net', 'Aldo Fabián Zamudio', '483111327', NULL, 22, NULL, 81.44, 2, 0, NULL, NULL, NULL, NULL, false, 'nuevo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli53@s.whatsapp.net', 'Cristóbal Andrés Mejía', '495680561', NULL, 22, NULL, 107.60, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-cli54@s.whatsapp.net', 'Rubén Darío Escalante', '474731627', NULL, 27, NULL, 190.94, 1, 0, NULL, NULL, NULL, NULL, false, 'inactivo', '2026-09-25 18:20:03.93509');
INSERT INTO public.barber_clientes (jid, nombre, telefono, primera_visita, visitas, ultima_visita, ticket_promedio, no_shows, cancelaciones_tardias, servicio_habitual, barbero_preferido, nota_interna, fecha_nacimiento, marketing_ok, etiqueta, creado_en) VALUES ('verif-vip@s.whatsapp.net', 'Cliente de Gasto Altísimo (VIP histórico)', '4521234567', NULL, 64, NULL, 1180.50, 0, 0, NULL, NULL, NULL, NULL, false, 'vip', '2026-09-25 18:20:03.93509');


--
-- PostgreSQL database dump complete
--

\unrestrict jkf6zoVnQcuKoCEs7h7tXjajYyG8118KgO8qRQf69o6Kjv9xbZ1GkquKAiq5YAr

